[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Let the Next.js plugin handle all routing automatically
# No manual redirects needed - the plugin knows how to route Next.js apps
