[build]
  command = "npm run netlify-build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# API redirects for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/next"
  status = 200

# Handle Next.js routing - this should come after API redirects
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/next"
  status = 200

[[headers]]
  for = "/sw.js"
  [headers.values]
  Cache-Control = "no-store, must-revalidate"

# Optional: prevent over-caching of HTML during debugging
[[headers]]
  for = "/*.html"
  [headers.values]
  Cache-Control = "no-store"
